/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.awt.*;
import java.io.IOException;
import java.util.*;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {

        System.out.println("Running train booking System");
        Scanner sc=new Scanner(System.in);
        int option=0;
        UserBookingService userBookingService;
        try{
            userBookingService =new UserBookingService();
        } catch (IOException e) {
            System.out.println("There is something wrong");
            return ;
        }

        while(option!=7){
            System.out.println("Enter 1 -> REGISTER AS NEW USER");
            System.out.println("Enter 2 -> LOGIN AS EXISTING USER");
            System.out.println("Enter 3 -> FETCH YOUR BOOKINGS");
            System.out.println("Enter 4 -> BOOK A TICKET");
            System.out.println("Enter 6 -> CANCEL MY TICKET");
            System.out.println("Enter 5 -> BOOK YOUR SEAT");
            System.out.println("Enter 7 -> EXIT THE APP");
            Train trainSelectedForBooking = new Train();
            option=sc.nextInt();
            switch(option){
                case 1:System.out.println("Enter USERNAME to SIGNUP");
                    String nameToSignUp = sc.nextLine();
                    System.out.println("Enter Password TO SIGNUP");
                    String passwordToSignUp=sc.nextLine();
                    User userToSignUp=new User(nameToSignUp,passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;
                case 2:System.out.println("Enter USERNAME to LOGIN");
                    String nameToLogin = sc.nextLine();
                    System.out.println("Enter Password TO LOGIN");
                    String passwordToLogin=sc.nextLine();
                    User userToLogin= new User(nameToLogin,passwordToLogin, UserServiceUtil.hashPassword(passwordToLogin),new ArrayList<>(), UUID.randomUUID().toString());
                    try{
                        userBookingService=new UserBookingService(userToLogin);
                    }
                    catch (IOException ex){
                        return;
                    }
                    break;
                    
                case 3:
                    System.out.println("fetching Your Bookings");
                    userBookingService.fetchBookings();
                    break;
                case 4:System.out.println("ENTER SOURCE:");
                    String source = sc.nextLine();
                    System.out.println("ENTER DESTINATION");
                    String dest = sc.nextLine();
                    System.out.println("ENTER DATE OF TRAVEL (YYYY-MM-DD)");
                    String dateOfTravel = sc.nextLine();
                    List<Train> trains = userBookingService.getTrains(source,dest); // This should be replaced with actual train fetching logic

                    int index =1;
                    for(Train t: trains){
                        System.out.println(index+"Train ID"+ t.getTrainId());
                        for(Map.Entry<String, String> entry: t.getStationTime().entrySet()) {
                            System.out.println("station "+entry.getKey()+" time: "+entry.getValue());
                        }
                    }
                    System.out.println("Select a train by typing 1,2,3...");
                    trainSelectedForBooking = trains.get(sc.nextInt());
                    break;
                    
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = sc.nextInt();
                    System.out.println("Enter the column");
                    int col = sc.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;

                case 6:
                    System.out.println("enter your train id to cancel the ticket");
                    String trainIdToCancel = sc.nextLine();
                    boolean isCancelled = userBookingService.canceltickets(trainIdToCancel);
                    if(isCancelled) {
                        System.out.println("Ticket cancelled successfully.");
                    } else {
                        System.out.println("Ticket cancellation failed.");
                    }
                    break;

                case 7: System.exit(0);
            }
        }
    }
}

